// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://racxzxmsigkfavtzycgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhY3h6eG1zaWdrZmF2dHp5Y2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjQyNjUsImV4cCI6MjA1ODU0MDI2NX0.YD5LprfYfZUhQ4IHqUBDnANQNAYrHWH6Rk7gbiLJ6WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);